name: deepsea-project-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.83=py310h2372a71_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - curl=8.5.0=hdbd6064_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=8.5.0=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_5
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - gast==0.5.4
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.11.0
      - idna==3.7
      - joblib==1.4.0
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - ml-dtypes==0.2.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - plotly==5.20.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - six==1.16.0
      - tenacity==8.2.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.2
      - wrapt==1.14.1
prefix: /home/tiago/anaconda3/envs/deepsea-project-cpu
